/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity;


import com.jiubredeemer.itemstorage.dal.entity.tables.BundlePurchase;
import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTag;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTagRelation;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemsUser;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items_24;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money;
import com.jiubredeemer.itemstorage.dal.entity.tables.RoomBundle;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in itemstorage.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BUNDLE_PURCHASE_BUNDLE_IDX = Internal.createIndex(DSL.name("bundle_purchase_bundle_idx"), BundlePurchase.BUNDLE_PURCHASE, new OrderField[] { BundlePurchase.BUNDLE_PURCHASE.ITEM_BUNDLE_ID }, false);
    public static final Index IDX_ITEM_TAG_RELATION_TAG_ID = Internal.createIndex(DSL.name("idx_item_tag_relation_tag_id"), ItemTagRelation.ITEM_TAG_RELATION, new OrderField[] { ItemTagRelation.ITEM_TAG_RELATION.TAG_ID }, false);
    public static final Index IDX_ITEM_TAG_ROOM_ID = Internal.createIndex(DSL.name("idx_item_tag_room_id"), ItemTag.ITEM_TAG, new OrderField[] { ItemTag.ITEM_TAG.ROOM_ID }, false);
    public static final Index IN_USE_IDX = Internal.createIndex(DSL.name("in_use_idx"), InventoryItem.INVENTORY_ITEM, new OrderField[] { InventoryItem.INVENTORY_ITEM.IN_USE }, false);
    public static final Index INVENTORY_CHARACTER_ID_IDX = Internal.createIndex(DSL.name("inventory_character_id_idx"), Inventory.INVENTORY, new OrderField[] { Inventory.INVENTORY.CHARACTER_ID }, false);
    public static final Index INVENTORY_ROOM_ID_IDX = Internal.createIndex(DSL.name("inventory_room_id_idx"), Inventory.INVENTORY, new OrderField[] { Inventory.INVENTORY.ROOM_ID }, false);
    public static final Index ITEM_STATS_ITEM_ID_IDX = Internal.createIndex(DSL.name("item_stats_item_id_idx"), ItemStats.ITEM_STATS, new OrderField[] { ItemStats.ITEM_STATS.ITEM_ID }, true);
    public static final Index ITEMS_24_TYPE_IDX = Internal.createIndex(DSL.name("items_24_type_idx"), Items_24.ITEMS_24, new OrderField[] { Items_24.ITEMS_24.TYPE }, false);
    public static final Index ITEMS_TYPE_IDX = Internal.createIndex(DSL.name("items_type_idx"), Items.ITEMS, new OrderField[] { Items.ITEMS.TYPE }, false);
    public static final Index ITEMS_USER_TYPE_IDX = Internal.createIndex(DSL.name("items_user_type_idx"), ItemsUser.ITEMS_USER, new OrderField[] { ItemsUser.ITEMS_USER.TYPE }, false);
    public static final Index MONEY_INVENTORY_ID = Internal.createIndex(DSL.name("money_inventory_id"), Money.MONEY, new OrderField[] { Money.MONEY.INVENTORY_ID }, false);
    public static final Index ROOM_BUNDLE_ROOM_ID = Internal.createIndex(DSL.name("room_bundle_room_id"), RoomBundle.ROOM_BUNDLE, new OrderField[] { RoomBundle.ROOM_BUNDLE.ROOM_ID }, false);
}
