/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity;


import com.jiubredeemer.itemstorage.dal.entity.tables.BundlePurchase;
import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItemSkill;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundled;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemSkill;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTag;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTagRelation;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemsUser;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items_24;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money;
import com.jiubredeemer.itemstorage.dal.entity.tables.RoomBundle;
import com.jiubredeemer.itemstorage.dal.entity.tables.Shop;
import com.jiubredeemer.itemstorage.dal.entity.tables.ShopItem;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Itemstorage extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage</code>
     */
    public static final Itemstorage ITEMSTORAGE = new Itemstorage();

    /**
     * The table <code>itemstorage.bundle_purchase</code>.
     */
    public final BundlePurchase BUNDLE_PURCHASE = BundlePurchase.BUNDLE_PURCHASE;

    /**
     * The table <code>itemstorage.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>itemstorage.inventory_item</code>.
     */
    public final InventoryItem INVENTORY_ITEM = InventoryItem.INVENTORY_ITEM;

    /**
     * The table <code>itemstorage.inventory_item_skill</code>.
     */
    public final InventoryItemSkill INVENTORY_ITEM_SKILL = InventoryItemSkill.INVENTORY_ITEM_SKILL;

    /**
     * The table <code>itemstorage.item_bundle</code>.
     */
    public final ItemBundle ITEM_BUNDLE = ItemBundle.ITEM_BUNDLE;

    /**
     * The table <code>itemstorage.item_bundled</code>.
     */
    public final ItemBundled ITEM_BUNDLED = ItemBundled.ITEM_BUNDLED;

    /**
     * The table <code>itemstorage.item_skill</code>.
     */
    public final ItemSkill ITEM_SKILL = ItemSkill.ITEM_SKILL;

    /**
     * The table <code>itemstorage.item_stats</code>.
     */
    public final ItemStats ITEM_STATS = ItemStats.ITEM_STATS;

    /**
     * The table <code>itemstorage.item_tag</code>.
     */
    public final ItemTag ITEM_TAG = ItemTag.ITEM_TAG;

    /**
     * The table <code>itemstorage.item_tag_relation</code>.
     */
    public final ItemTagRelation ITEM_TAG_RELATION = ItemTagRelation.ITEM_TAG_RELATION;

    /**
     * The table <code>itemstorage.items</code>.
     */
    public final Items ITEMS = Items.ITEMS;

    /**
     * The table <code>itemstorage.items_24</code>.
     */
    public final Items_24 ITEMS_24 = Items_24.ITEMS_24;

    /**
     * The table <code>itemstorage.items_user</code>.
     */
    public final ItemsUser ITEMS_USER = ItemsUser.ITEMS_USER;

    /**
     * The table <code>itemstorage.money</code>.
     */
    public final Money MONEY = Money.MONEY;

    /**
     * The table <code>itemstorage.room_bundle</code>.
     */
    public final RoomBundle ROOM_BUNDLE = RoomBundle.ROOM_BUNDLE;

    /**
     * The table <code>itemstorage.shop</code>.
     */
    public final Shop SHOP = Shop.SHOP;

    /**
     * The table <code>itemstorage.shop_item</code>.
     */
    public final ShopItem SHOP_ITEM = ShopItem.SHOP_ITEM;

    /**
     * No further instances allowed
     */
    private Itemstorage() {
        super("itemstorage", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BundlePurchase.BUNDLE_PURCHASE,
            Inventory.INVENTORY,
            InventoryItem.INVENTORY_ITEM,
            InventoryItemSkill.INVENTORY_ITEM_SKILL,
            ItemBundle.ITEM_BUNDLE,
            ItemBundled.ITEM_BUNDLED,
            ItemSkill.ITEM_SKILL,
            ItemStats.ITEM_STATS,
            ItemTag.ITEM_TAG,
            ItemTagRelation.ITEM_TAG_RELATION,
            Items.ITEMS,
            Items_24.ITEMS_24,
            ItemsUser.ITEMS_USER,
            Money.MONEY,
            RoomBundle.ROOM_BUNDLE,
            Shop.SHOP,
            ShopItem.SHOP_ITEM
        );
    }
}
