/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity;


import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Itemstorage extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage</code>
     */
    public static final Itemstorage ITEMSTORAGE = new Itemstorage();

    /**
     * The table <code>itemstorage.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>itemstorage.inventory_item</code>.
     */
    public final InventoryItem INVENTORY_ITEM = InventoryItem.INVENTORY_ITEM;

    /**
     * The table <code>itemstorage.item_stats</code>.
     */
    public final ItemStats ITEM_STATS = ItemStats.ITEM_STATS;

    /**
     * The table <code>itemstorage.items</code>.
     */
    public final Items ITEMS = Items.ITEMS;

    /**
     * The table <code>itemstorage.money</code>.
     */
    public final Money MONEY = Money.MONEY;

    /**
     * No further instances allowed
     */
    private Itemstorage() {
        super("itemstorage", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Inventory.INVENTORY,
            InventoryItem.INVENTORY_ITEM,
            ItemStats.ITEM_STATS,
            Items.ITEMS,
            Money.MONEY
        );
    }
}
