/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity;


import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money;


/**
 * Convenience access to all tables in itemstorage.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>itemstorage.inventory</code>.
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>itemstorage.inventory_item</code>.
     */
    public static final InventoryItem INVENTORY_ITEM = InventoryItem.INVENTORY_ITEM;

    /**
     * The table <code>itemstorage.items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;

    /**
     * The table <code>itemstorage.money</code>.
     */
    public static final Money MONEY = Money.MONEY;
}
