/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity;


import com.jiubredeemer.itemstorage.dal.entity.tables.BundlePurchase;
import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItemSkill;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundled;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemSkill;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTag;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTagRelation;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemsUser;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items_24;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money;
import com.jiubredeemer.itemstorage.dal.entity.tables.RoomBundle;


/**
 * Convenience access to all tables in itemstorage.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>itemstorage.bundle_purchase</code>.
     */
    public static final BundlePurchase BUNDLE_PURCHASE = BundlePurchase.BUNDLE_PURCHASE;

    /**
     * The table <code>itemstorage.inventory</code>.
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>itemstorage.inventory_item</code>.
     */
    public static final InventoryItem INVENTORY_ITEM = InventoryItem.INVENTORY_ITEM;

    /**
     * The table <code>itemstorage.inventory_item_skill</code>.
     */
    public static final InventoryItemSkill INVENTORY_ITEM_SKILL = InventoryItemSkill.INVENTORY_ITEM_SKILL;

    /**
     * The table <code>itemstorage.item_bundle</code>.
     */
    public static final ItemBundle ITEM_BUNDLE = ItemBundle.ITEM_BUNDLE;

    /**
     * The table <code>itemstorage.item_bundled</code>.
     */
    public static final ItemBundled ITEM_BUNDLED = ItemBundled.ITEM_BUNDLED;

    /**
     * The table <code>itemstorage.item_skill</code>.
     */
    public static final ItemSkill ITEM_SKILL = ItemSkill.ITEM_SKILL;

    /**
     * The table <code>itemstorage.item_stats</code>.
     */
    public static final ItemStats ITEM_STATS = ItemStats.ITEM_STATS;

    /**
     * The table <code>itemstorage.item_tag</code>.
     */
    public static final ItemTag ITEM_TAG = ItemTag.ITEM_TAG;

    /**
     * The table <code>itemstorage.item_tag_relation</code>.
     */
    public static final ItemTagRelation ITEM_TAG_RELATION = ItemTagRelation.ITEM_TAG_RELATION;

    /**
     * The table <code>itemstorage.items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;

    /**
     * The table <code>itemstorage.items_24</code>.
     */
    public static final Items_24 ITEMS_24 = Items_24.ITEMS_24;

    /**
     * The table <code>itemstorage.items_user</code>.
     */
    public static final ItemsUser ITEMS_USER = ItemsUser.ITEMS_USER;

    /**
     * The table <code>itemstorage.money</code>.
     */
    public static final Money MONEY = Money.MONEY;

    /**
     * The table <code>itemstorage.room_bundle</code>.
     */
    public static final RoomBundle ROOM_BUNDLE = RoomBundle.ROOM_BUNDLE;
}
