/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.BundlePurchase;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BundlePurchaseRecord extends UpdatableRecordImpl<BundlePurchaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.bundle_purchase.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.bundle_purchase.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.bundle_purchase.item_bundle_id</code>.
     */
    public void setItemBundleId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.bundle_purchase.item_bundle_id</code>.
     */
    public UUID getItemBundleId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.bundle_purchase.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.bundle_purchase.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BundlePurchaseRecord
     */
    public BundlePurchaseRecord() {
        super(BundlePurchase.BUNDLE_PURCHASE);
    }

    /**
     * Create a detached, initialised BundlePurchaseRecord
     */
    public BundlePurchaseRecord(UUID userId, UUID itemBundleId, LocalDateTime createdAt) {
        super(BundlePurchase.BUNDLE_PURCHASE);

        setUserId(userId);
        setItemBundleId(itemBundleId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
