/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItemSkill;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryItemSkillRecord extends UpdatableRecordImpl<InventoryItemSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.inventory_item_skill.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item_skill.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>itemstorage.inventory_item_skill.inventory_item_id</code>.
     */
    public void setInventoryItemId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>itemstorage.inventory_item_skill.inventory_item_id</code>.
     */
    public UUID getInventoryItemId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.inventory_item_skill.item_skill_id</code>.
     */
    public void setItemSkillId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item_skill.item_skill_id</code>.
     */
    public UUID getItemSkillId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>itemstorage.inventory_item_skill.current_charges</code>.
     */
    public void setCurrentCharges(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item_skill.current_charges</code>.
     */
    public Integer getCurrentCharges() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryItemSkillRecord
     */
    public InventoryItemSkillRecord() {
        super(InventoryItemSkill.INVENTORY_ITEM_SKILL);
    }

    /**
     * Create a detached, initialised InventoryItemSkillRecord
     */
    public InventoryItemSkillRecord(UUID id, UUID inventoryItemId, UUID itemSkillId, Integer currentCharges) {
        super(InventoryItemSkill.INVENTORY_ITEM_SKILL);

        setId(id);
        setInventoryItemId(inventoryItemId);
        setItemSkillId(itemSkillId);
        setCurrentCharges(currentCharges);
        resetChangedOnNotNull();
    }
}
