/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryItemRecord extends UpdatableRecordImpl<InventoryItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.inventory_item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.inventory_id</code>.
     */
    public void setInventoryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.inventory_id</code>.
     */
    public UUID getInventoryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.count</code>.
     */
    public void setCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.count</code>.
     */
    public Long getCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.in_use</code>.
     */
    public void setInUse(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.in_use</code>.
     */
    public Boolean getInUse() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.attack_bonus_value</code>.
     */
    public void setAttackBonusValue(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.attack_bonus_value</code>.
     */
    public Long getAttackBonusValue() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.damage_bonus_value</code>.
     */
    public void setDamageBonusValue(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.damage_bonus_value</code>.
     */
    public Long getDamageBonusValue() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>itemstorage.inventory_item.identified</code>.
     */
    public void setIdentified(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.inventory_item.identified</code>.
     */
    public Boolean getIdentified() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryItemRecord
     */
    public InventoryItemRecord() {
        super(InventoryItem.INVENTORY_ITEM);
    }

    /**
     * Create a detached, initialised InventoryItemRecord
     */
    public InventoryItemRecord(UUID id, UUID inventoryId, UUID itemId, Long count, Boolean inUse, Long attackBonusValue, Long damageBonusValue, Boolean identified) {
        super(InventoryItem.INVENTORY_ITEM);

        setId(id);
        setInventoryId(inventoryId);
        setItemId(itemId);
        setCount(count);
        setInUse(inUse);
        setAttackBonusValue(attackBonusValue);
        setDamageBonusValue(damageBonusValue);
        setIdentified(identified);
        resetChangedOnNotNull();
    }
}
