/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.inventory.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.inventory.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.inventory.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.inventory.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.inventory.character_id</code>.
     */
    public void setCharacterId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.inventory.character_id</code>.
     */
    public UUID getCharacterId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>itemstorage.inventory.total_weight</code>.
     */
    public void setTotalWeight(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.inventory.total_weight</code>.
     */
    public Long getTotalWeight() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(UUID id, UUID roomId, UUID characterId, Long totalWeight) {
        super(Inventory.INVENTORY);

        setId(id);
        setRoomId(roomId);
        setCharacterId(characterId);
        setTotalWeight(totalWeight);
        resetChangedOnNotNull();
    }
}
