/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemSkill;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemSkillRecord extends UpdatableRecordImpl<ItemSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_skill.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_skill.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.item_skill.name</code>.
     */
    public void setName(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.name</code>.
     */
    public JSONB getName() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>itemstorage.item_skill.cast_time</code>.
     */
    public void setCastTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.cast_time</code>.
     */
    public String getCastTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>itemstorage.item_skill.distance</code>.
     */
    public void setDistance(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.distance</code>.
     */
    public String getDistance() {
        return (String) get(4);
    }

    /**
     * Setter for <code>itemstorage.item_skill.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>itemstorage.item_skill.short_description</code>.
     */
    public void setShortDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.short_description</code>.
     */
    public String getShortDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>itemstorage.item_skill.charges</code>.
     */
    public void setCharges(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.charges</code>.
     */
    public Integer getCharges() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>itemstorage.item_skill.charges_refill</code>.
     */
    public void setChargesRefill(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.charges_refill</code>.
     */
    public String getChargesRefill() {
        return (String) get(8);
    }

    /**
     * Setter for <code>itemstorage.item_skill.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>itemstorage.item_skill.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemSkillRecord
     */
    public ItemSkillRecord() {
        super(ItemSkill.ITEM_SKILL);
    }

    /**
     * Create a detached, initialised ItemSkillRecord
     */
    public ItemSkillRecord(UUID id, UUID itemId, JSONB name, String castTime, String distance, String description, String shortDescription, Integer charges, String chargesRefill, String imgUrl) {
        super(ItemSkill.ITEM_SKILL);

        setId(id);
        setItemId(itemId);
        setName(name);
        setCastTime(castTime);
        setDistance(distance);
        setDescription(description);
        setShortDescription(shortDescription);
        setCharges(charges);
        setChargesRefill(chargesRefill);
        setImgUrl(imgUrl);
        resetChangedOnNotNull();
    }
}
