/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTag;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemTagRecord extends UpdatableRecordImpl<ItemTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_tag.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_tag.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>itemstorage.item_tag.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>itemstorage.item_tag.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemTagRecord
     */
    public ItemTagRecord() {
        super(ItemTag.ITEM_TAG);
    }

    /**
     * Create a detached, initialised ItemTagRecord
     */
    public ItemTagRecord(UUID id, String name, String description, UUID roomId) {
        super(ItemTag.ITEM_TAG);

        setId(id);
        setName(name);
        setDescription(description);
        setRoomId(roomId);
        resetChangedOnNotNull();
    }
}
