/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemBundleRecord extends UpdatableRecordImpl<ItemBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_bundle.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.owner_user_id</code>.
     */
    public void setOwnerUserId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.owner_user_id</code>.
     */
    public UUID getOwnerUserId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.is_public</code>.
     */
    public void setIsPublic(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.is_public</code>.
     */
    public Boolean getIsPublic() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>itemstorage.item_bundle.price_crystals</code>.
     */
    public void setPriceCrystals(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundle.price_crystals</code>.
     */
    public Integer getPriceCrystals() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemBundleRecord
     */
    public ItemBundleRecord() {
        super(ItemBundle.ITEM_BUNDLE);
    }

    /**
     * Create a detached, initialised ItemBundleRecord
     */
    public ItemBundleRecord(UUID id, String name, String description, LocalDateTime createdAt, String imgUrl, UUID ownerUserId, Boolean isPublic, Integer priceCrystals) {
        super(ItemBundle.ITEM_BUNDLE);

        setId(id);
        setName(name);
        setDescription(description);
        setCreatedAt(createdAt);
        setImgUrl(imgUrl);
        setOwnerUserId(ownerUserId);
        setIsPublic(isPublic);
        setPriceCrystals(priceCrystals);
        resetChangedOnNotNull();
    }
}
