/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.Items;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemsRecord extends UpdatableRecordImpl<ItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.items.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.items.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.items.name</code>.
     */
    public void setName(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.items.name</code>.
     */
    public JSONB getName() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>itemstorage.items.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.items.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>itemstorage.items.subtype</code>.
     */
    public void setSubtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.items.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>itemstorage.items.customization</code>.
     */
    public void setCustomization(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.items.customization</code>.
     */
    public Boolean getCustomization() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>itemstorage.items.rarity</code>.
     */
    public void setRarity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.items.rarity</code>.
     */
    public String getRarity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>itemstorage.items.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.items.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>itemstorage.items.stats</code>.
     */
    public void setStats(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.items.stats</code>.
     */
    public JSONB getStats() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>itemstorage.items.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>itemstorage.items.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>itemstorage.items.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>itemstorage.items.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>itemstorage.items.creator_id</code>.
     */
    public void setCreatorId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>itemstorage.items.creator_id</code>.
     */
    public UUID getCreatorId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>itemstorage.items.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>itemstorage.items.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>itemstorage.items.visible_for_players</code>.
     */
    public void setVisibleForPlayers(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>itemstorage.items.visible_for_players</code>.
     */
    public Boolean getVisibleForPlayers() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemsRecord
     */
    public ItemsRecord() {
        super(Items.ITEMS);
    }

    /**
     * Create a detached, initialised ItemsRecord
     */
    public ItemsRecord(UUID id, JSONB name, String type, String subtype, Boolean customization, String rarity, String description, JSONB stats, LocalDateTime createdAt, UUID roomId, UUID creatorId, String imgUrl, Boolean visibleForPlayers) {
        super(Items.ITEMS);

        setId(id);
        setName(name);
        setType(type);
        setSubtype(subtype);
        setCustomization(customization);
        setRarity(rarity);
        setDescription(description);
        setStats(stats);
        setCreatedAt(createdAt);
        setRoomId(roomId);
        setCreatorId(creatorId);
        setImgUrl(imgUrl);
        setVisibleForPlayers(visibleForPlayers);
        resetChangedOnNotNull();
    }
}
