/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.Items_24;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Items_24Record extends UpdatableRecordImpl<Items_24Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.items_24.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.items_24.name</code>.
     */
    public void setName(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.name</code>.
     */
    public JSONB getName() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>itemstorage.items_24.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>itemstorage.items_24.subtype</code>.
     */
    public void setSubtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>itemstorage.items_24.customization</code>.
     */
    public void setCustomization(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.customization</code>.
     */
    public Boolean getCustomization() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>itemstorage.items_24.rarity</code>.
     */
    public void setRarity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.rarity</code>.
     */
    public String getRarity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>itemstorage.items_24.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>itemstorage.items_24.stats</code>.
     */
    public void setStats(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.stats</code>.
     */
    public JSONB getStats() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>itemstorage.items_24.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>itemstorage.items_24.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>itemstorage.items_24.creator_id</code>.
     */
    public void setCreatorId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.creator_id</code>.
     */
    public UUID getCreatorId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>itemstorage.items_24.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>itemstorage.items_24.visible_for_players</code>.
     */
    public void setVisibleForPlayers(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.visible_for_players</code>.
     */
    public Boolean getVisibleForPlayers() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>itemstorage.items_24.creator</code>.
     */
    public void setCreator(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.creator</code>.
     */
    public String getCreator() {
        return (String) get(13);
    }

    /**
     * Setter for <code>itemstorage.items_24.description_eng</code>.
     */
    public void setDescriptionEng(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.description_eng</code>.
     */
    public String getDescriptionEng() {
        return (String) get(14);
    }

    /**
     * Setter for <code>itemstorage.items_24.source</code>.
     */
    public void setSource(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>itemstorage.items_24.source</code>.
     */
    public String getSource() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Items_24Record
     */
    public Items_24Record() {
        super(Items_24.ITEMS_24);
    }

    /**
     * Create a detached, initialised Items_24Record
     */
    public Items_24Record(UUID id, JSONB name, String type, String subtype, Boolean customization, String rarity, String description, JSONB stats, LocalDateTime createdAt, UUID roomId, UUID creatorId, String imgUrl, Boolean visibleForPlayers, String creator, String descriptionEng, String source) {
        super(Items_24.ITEMS_24);

        setId(id);
        setName(name);
        setType(type);
        setSubtype(subtype);
        setCustomization(customization);
        setRarity(rarity);
        setDescription(description);
        setStats(stats);
        setCreatedAt(createdAt);
        setRoomId(roomId);
        setCreatorId(creatorId);
        setImgUrl(imgUrl);
        setVisibleForPlayers(visibleForPlayers);
        setCreator(creator);
        setDescriptionEng(descriptionEng);
        setSource(source);
        resetChangedOnNotNull();
    }
}
