/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemTagRelation;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemTagRelationRecord extends UpdatableRecordImpl<ItemTagRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_tag_relation.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag_relation.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_tag_relation.tag_id</code>.
     */
    public void setTagId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_tag_relation.tag_id</code>.
     */
    public UUID getTagId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemTagRelationRecord
     */
    public ItemTagRelationRecord() {
        super(ItemTagRelation.ITEM_TAG_RELATION);
    }

    /**
     * Create a detached, initialised ItemTagRelationRecord
     */
    public ItemTagRelationRecord(UUID itemId, UUID tagId) {
        super(ItemTagRelation.ITEM_TAG_RELATION);

        setItemId(itemId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }
}
