/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundled;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemBundledRecord extends UpdatableRecordImpl<ItemBundledRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_bundled.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.item_bundle_id</code>.
     */
    public void setItemBundleId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.item_bundle_id</code>.
     */
    public UUID getItemBundleId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.name</code>.
     */
    public void setName(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.name</code>.
     */
    public JSONB getName() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.subtype</code>.
     */
    public void setSubtype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.customization</code>.
     */
    public void setCustomization(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.customization</code>.
     */
    public Boolean getCustomization() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.rarity</code>.
     */
    public void setRarity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.rarity</code>.
     */
    public String getRarity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.stats</code>.
     */
    public void setStats(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.stats</code>.
     */
    public JSONB getStats() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.creator_id</code>.
     */
    public void setCreatorId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.creator_id</code>.
     */
    public UUID getCreatorId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.visible_for_players</code>.
     */
    public void setVisibleForPlayers(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.visible_for_players</code>.
     */
    public Boolean getVisibleForPlayers() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.creator</code>.
     */
    public void setCreator(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.creator</code>.
     */
    public String getCreator() {
        return (String) get(13);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.description_eng</code>.
     */
    public void setDescriptionEng(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.description_eng</code>.
     */
    public String getDescriptionEng() {
        return (String) get(14);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.historical</code>.
     */
    public void setHistorical(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.historical</code>.
     */
    public Boolean getHistorical() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.hidden_stats</code>.
     */
    public void setHiddenStats(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.hidden_stats</code>.
     */
    public Boolean getHiddenStats() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>itemstorage.item_bundled.unidentified_item_id</code>.
     */
    public void setUnidentifiedItemId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>itemstorage.item_bundled.unidentified_item_id</code>.
     */
    public UUID getUnidentifiedItemId() {
        return (UUID) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemBundledRecord
     */
    public ItemBundledRecord() {
        super(ItemBundled.ITEM_BUNDLED);
    }

    /**
     * Create a detached, initialised ItemBundledRecord
     */
    public ItemBundledRecord(UUID id, UUID itemBundleId, JSONB name, String type, String subtype, Boolean customization, String rarity, String description, JSONB stats, LocalDateTime createdAt, UUID creatorId, String imgUrl, Boolean visibleForPlayers, String creator, String descriptionEng, Boolean historical, Boolean hiddenStats, UUID unidentifiedItemId) {
        super(ItemBundled.ITEM_BUNDLED);

        setId(id);
        setItemBundleId(itemBundleId);
        setName(name);
        setType(type);
        setSubtype(subtype);
        setCustomization(customization);
        setRarity(rarity);
        setDescription(description);
        setStats(stats);
        setCreatedAt(createdAt);
        setCreatorId(creatorId);
        setImgUrl(imgUrl);
        setVisibleForPlayers(visibleForPlayers);
        setCreator(creator);
        setDescriptionEng(descriptionEng);
        setHistorical(historical);
        setHiddenStats(hiddenStats);
        setUnidentifiedItemId(unidentifiedItemId);
        resetChangedOnNotNull();
    }
}
