/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemStatsRecord extends UpdatableRecordImpl<ItemStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.item_stats.id</code>. Уникальный
     * идентификатор записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.id</code>. Уникальный
     * идентификатор записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.item_stats.item_id</code>. Уникальный
     * идентификатор предмета
     */
    public void setItemId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.item_id</code>. Уникальный
     * идентификатор предмета
     */
    public UUID getItemId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.item_stats.armory_class</code>. Класс брони,
     * даваемый предметом
     */
    public void setArmoryClass(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.armory_class</code>. Класс брони,
     * даваемый предметом
     */
    public JSONB getArmoryClass() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>itemstorage.item_stats.speed</code>. Скорость даваемая
     * предметом
     */
    public void setSpeed(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.speed</code>. Скорость даваемая
     * предметом
     */
    public JSONB getSpeed() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>itemstorage.item_stats.hp</code>. ХП даваемое предметом
     */
    public void setHp(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.hp</code>. ХП даваемое предметом
     */
    public JSONB getHp() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>itemstorage.item_stats.saving_throw</code>. Спасброски
     * даваемые предметом
     */
    public void setSavingThrow(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.saving_throw</code>. Спасброски
     * даваемые предметом
     */
    public JSONB getSavingThrow() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>itemstorage.item_stats.adventage</code>.
     */
    public void setAdventage(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.adventage</code>.
     */
    public JSONB getAdventage() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>itemstorage.item_stats.interference</code>.
     */
    public void setInterference(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.interference</code>.
     */
    public JSONB getInterference() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>itemstorage.item_stats.resistance</code>.
     */
    public void setResistance(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.resistance</code>.
     */
    public JSONB getResistance() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>itemstorage.item_stats.vulnerability</code>.
     */
    public void setVulnerability(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.vulnerability</code>.
     */
    public JSONB getVulnerability() {
        return (JSONB) get(9);
    }

    /**
     * Setter for <code>itemstorage.item_stats.immunity</code>.
     */
    public void setImmunity(JSONB value) {
        set(10, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.immunity</code>.
     */
    public JSONB getImmunity() {
        return (JSONB) get(10);
    }

    /**
     * Setter for <code>itemstorage.item_stats.ability_score</code>.
     */
    public void setAbilityScore(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.ability_score</code>.
     */
    public JSONB getAbilityScore() {
        return (JSONB) get(11);
    }

    /**
     * Setter for <code>itemstorage.item_stats.proficiency_skill</code>.
     */
    public void setProficiencySkill(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.proficiency_skill</code>.
     */
    public JSONB getProficiencySkill() {
        return (JSONB) get(12);
    }

    /**
     * Setter for <code>itemstorage.item_stats.attack_bonus</code>.
     */
    public void setAttackBonus(JSONB value) {
        set(13, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.attack_bonus</code>.
     */
    public JSONB getAttackBonus() {
        return (JSONB) get(13);
    }

    /**
     * Setter for <code>itemstorage.item_stats.damage_bonus</code>.
     */
    public void setDamageBonus(JSONB value) {
        set(14, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.damage_bonus</code>.
     */
    public JSONB getDamageBonus() {
        return (JSONB) get(14);
    }

    /**
     * Setter for <code>itemstorage.item_stats.limitation</code>.
     */
    public void setLimitation(JSONB value) {
        set(15, value);
    }

    /**
     * Getter for <code>itemstorage.item_stats.limitation</code>.
     */
    public JSONB getLimitation() {
        return (JSONB) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemStatsRecord
     */
    public ItemStatsRecord() {
        super(ItemStats.ITEM_STATS);
    }

    /**
     * Create a detached, initialised ItemStatsRecord
     */
    public ItemStatsRecord(UUID id, UUID itemId, JSONB armoryClass, JSONB speed, JSONB hp, JSONB savingThrow, JSONB adventage, JSONB interference, JSONB resistance, JSONB vulnerability, JSONB immunity, JSONB abilityScore, JSONB proficiencySkill, JSONB attackBonus, JSONB damageBonus, JSONB limitation) {
        super(ItemStats.ITEM_STATS);

        setId(id);
        setItemId(itemId);
        setArmoryClass(armoryClass);
        setSpeed(speed);
        setHp(hp);
        setSavingThrow(savingThrow);
        setAdventage(adventage);
        setInterference(interference);
        setResistance(resistance);
        setVulnerability(vulnerability);
        setImmunity(immunity);
        setAbilityScore(abilityScore);
        setProficiencySkill(proficiencySkill);
        setAttackBonus(attackBonus);
        setDamageBonus(damageBonus);
        setLimitation(limitation);
        resetChangedOnNotNull();
    }
}
