/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.Money;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MoneyRecord extends UpdatableRecordImpl<MoneyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.money.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.money.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.money.inventory_id</code>.
     */
    public void setInventoryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.money.inventory_id</code>.
     */
    public UUID getInventoryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.money.golden_count</code>.
     */
    public void setGoldenCount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.money.golden_count</code>.
     */
    public Long getGoldenCount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>itemstorage.money.silver_count</code>.
     */
    public void setSilverCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.money.silver_count</code>.
     */
    public Long getSilverCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>itemstorage.money.copper_count</code>.
     */
    public void setCopperCount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.money.copper_count</code>.
     */
    public Long getCopperCount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>itemstorage.money.electrum_count</code>.
     */
    public void setElectrumCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.money.electrum_count</code>.
     */
    public Long getElectrumCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>itemstorage.money.platinum_count</code>.
     */
    public void setPlatinumCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.money.platinum_count</code>.
     */
    public Long getPlatinumCount() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoneyRecord
     */
    public MoneyRecord() {
        super(Money.MONEY);
    }

    /**
     * Create a detached, initialised MoneyRecord
     */
    public MoneyRecord(UUID id, UUID inventoryId, Long goldenCount, Long silverCount, Long copperCount, Long electrumCount, Long platinumCount) {
        super(Money.MONEY);

        setId(id);
        setInventoryId(inventoryId);
        setGoldenCount(goldenCount);
        setSilverCount(silverCount);
        setCopperCount(copperCount);
        setElectrumCount(electrumCount);
        setPlatinumCount(platinumCount);
        resetChangedOnNotNull();
    }
}
