/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.RoomBundle;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomBundleRecord extends UpdatableRecordImpl<RoomBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.room_bundle.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.room_bundle.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.room_bundle.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.room_bundle.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.room_bundle.item_bundle_id</code>.
     */
    public void setItemBundleId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.room_bundle.item_bundle_id</code>.
     */
    public UUID getItemBundleId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomBundleRecord
     */
    public RoomBundleRecord() {
        super(RoomBundle.ROOM_BUNDLE);
    }

    /**
     * Create a detached, initialised RoomBundleRecord
     */
    public RoomBundleRecord(UUID id, UUID roomId, UUID itemBundleId) {
        super(RoomBundle.ROOM_BUNDLE);

        setId(id);
        setRoomId(roomId);
        setItemBundleId(itemBundleId);
        resetChangedOnNotNull();
    }
}
