/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.ShopItem;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopItemRecord extends UpdatableRecordImpl<ShopItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.shop_item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.shop_item.shop_id</code>.
     */
    public void setShopId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.shop_id</code>.
     */
    public UUID getShopId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.shop_item.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>itemstorage.shop_item.price_gold</code>.
     */
    public void setPriceGold(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.price_gold</code>.
     */
    public Long getPriceGold() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>itemstorage.shop_item.price_silver</code>.
     */
    public void setPriceSilver(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.price_silver</code>.
     */
    public Long getPriceSilver() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>itemstorage.shop_item.price_copper</code>.
     */
    public void setPriceCopper(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.price_copper</code>.
     */
    public Long getPriceCopper() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>itemstorage.shop_item.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>itemstorage.shop_item.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.shop_item.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopItemRecord
     */
    public ShopItemRecord() {
        super(ShopItem.SHOP_ITEM);
    }

    /**
     * Create a detached, initialised ShopItemRecord
     */
    public ShopItemRecord(UUID id, UUID shopId, UUID itemId, Long priceGold, Long priceSilver, Long priceCopper, Integer sortOrder, LocalDateTime createdAt) {
        super(ShopItem.SHOP_ITEM);

        setId(id);
        setShopId(shopId);
        setItemId(itemId);
        setPriceGold(priceGold);
        setPriceSilver(priceSilver);
        setPriceCopper(priceCopper);
        setSortOrder(sortOrder);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
