/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables.records;


import com.jiubredeemer.itemstorage.dal.entity.tables.Shop;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopRecord extends UpdatableRecordImpl<ShopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>itemstorage.shop.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>itemstorage.shop.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>itemstorage.shop.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>itemstorage.shop.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>itemstorage.shop.npc_id</code>.
     */
    public void setNpcId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>itemstorage.shop.npc_id</code>.
     */
    public UUID getNpcId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>itemstorage.shop.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>itemstorage.shop.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>itemstorage.shop.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>itemstorage.shop.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>itemstorage.shop.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>itemstorage.shop.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>itemstorage.shop.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>itemstorage.shop.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>itemstorage.shop.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>itemstorage.shop.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopRecord
     */
    public ShopRecord() {
        super(Shop.SHOP);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(UUID id, UUID roomId, UUID npcId, String name, String description, String imgUrl, UUID createdBy, LocalDateTime createdAt) {
        super(Shop.SHOP);

        setId(id);
        setRoomId(roomId);
        setNpcId(npcId);
        setName(name);
        setDescription(description);
        setImgUrl(imgUrl);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
