/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle.ItemBundlePath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.BundlePurchaseRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BundlePurchase extends TableImpl<BundlePurchaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.bundle_purchase</code>
     */
    public static final BundlePurchase BUNDLE_PURCHASE = new BundlePurchase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BundlePurchaseRecord> getRecordType() {
        return BundlePurchaseRecord.class;
    }

    /**
     * The column <code>itemstorage.bundle_purchase.user_id</code>.
     */
    public final TableField<BundlePurchaseRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.bundle_purchase.item_bundle_id</code>.
     */
    public final TableField<BundlePurchaseRecord, UUID> ITEM_BUNDLE_ID = createField(DSL.name("item_bundle_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.bundle_purchase.created_at</code>.
     */
    public final TableField<BundlePurchaseRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private BundlePurchase(Name alias, Table<BundlePurchaseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BundlePurchase(Name alias, Table<BundlePurchaseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.bundle_purchase</code> table
     * reference
     */
    public BundlePurchase(String alias) {
        this(DSL.name(alias), BUNDLE_PURCHASE);
    }

    /**
     * Create an aliased <code>itemstorage.bundle_purchase</code> table
     * reference
     */
    public BundlePurchase(Name alias) {
        this(alias, BUNDLE_PURCHASE);
    }

    /**
     * Create a <code>itemstorage.bundle_purchase</code> table reference
     */
    public BundlePurchase() {
        this(DSL.name("bundle_purchase"), null);
    }

    public <O extends Record> BundlePurchase(Table<O> path, ForeignKey<O, BundlePurchaseRecord> childPath, InverseForeignKey<O, BundlePurchaseRecord> parentPath) {
        super(path, childPath, parentPath, BUNDLE_PURCHASE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BundlePurchasePath extends BundlePurchase implements Path<BundlePurchaseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BundlePurchasePath(Table<O> path, ForeignKey<O, BundlePurchaseRecord> childPath, InverseForeignKey<O, BundlePurchaseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BundlePurchasePath(Name alias, Table<BundlePurchaseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BundlePurchasePath as(String alias) {
            return new BundlePurchasePath(DSL.name(alias), this);
        }

        @Override
        public BundlePurchasePath as(Name alias) {
            return new BundlePurchasePath(alias, this);
        }

        @Override
        public BundlePurchasePath as(Table<?> alias) {
            return new BundlePurchasePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BUNDLE_PURCHASE_BUNDLE_IDX);
    }

    @Override
    public UniqueKey<BundlePurchaseRecord> getPrimaryKey() {
        return Keys.BUNDLE_PURCHASE_PKEY;
    }

    @Override
    public List<ForeignKey<BundlePurchaseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BUNDLE_PURCHASE__FK_BUNDLE_PURCHASE_BUNDLE);
    }

    private transient ItemBundlePath _itemBundle;

    /**
     * Get the implicit join path to the <code>itemstorage.item_bundle</code>
     * table.
     */
    public ItemBundlePath itemBundle() {
        if (_itemBundle == null)
            _itemBundle = new ItemBundlePath(this, Keys.BUNDLE_PURCHASE__FK_BUNDLE_PURCHASE_BUNDLE, null);

        return _itemBundle;
    }

    @Override
    public BundlePurchase as(String alias) {
        return new BundlePurchase(DSL.name(alias), this);
    }

    @Override
    public BundlePurchase as(Name alias) {
        return new BundlePurchase(alias, this);
    }

    @Override
    public BundlePurchase as(Table<?> alias) {
        return new BundlePurchase(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BundlePurchase rename(String name) {
        return new BundlePurchase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BundlePurchase rename(Name name) {
        return new BundlePurchase(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BundlePurchase rename(Table<?> name) {
        return new BundlePurchase(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase where(Condition condition) {
        return new BundlePurchase(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BundlePurchase where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BundlePurchase where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BundlePurchase where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BundlePurchase where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BundlePurchase whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
