/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem.InventoryItemPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.Money.MoneyPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.InventoryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Inventory extends TableImpl<InventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.inventory</code>
     */
    public static final Inventory INVENTORY = new Inventory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryRecord> getRecordType() {
        return InventoryRecord.class;
    }

    /**
     * The column <code>itemstorage.inventory.id</code>.
     */
    public final TableField<InventoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory.room_id</code>.
     */
    public final TableField<InventoryRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory.character_id</code>.
     */
    public final TableField<InventoryRecord, UUID> CHARACTER_ID = createField(DSL.name("character_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory.total_weight</code>.
     */
    public final TableField<InventoryRecord, Long> TOTAL_WEIGHT = createField(DSL.name("total_weight"), SQLDataType.BIGINT.nullable(false), this, "");

    private Inventory(Name alias, Table<InventoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Inventory(Name alias, Table<InventoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.inventory</code> table reference
     */
    public Inventory(String alias) {
        this(DSL.name(alias), INVENTORY);
    }

    /**
     * Create an aliased <code>itemstorage.inventory</code> table reference
     */
    public Inventory(Name alias) {
        this(alias, INVENTORY);
    }

    /**
     * Create a <code>itemstorage.inventory</code> table reference
     */
    public Inventory() {
        this(DSL.name("inventory"), null);
    }

    public <O extends Record> Inventory(Table<O> path, ForeignKey<O, InventoryRecord> childPath, InverseForeignKey<O, InventoryRecord> parentPath) {
        super(path, childPath, parentPath, INVENTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InventoryPath extends Inventory implements Path<InventoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InventoryPath(Table<O> path, ForeignKey<O, InventoryRecord> childPath, InverseForeignKey<O, InventoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InventoryPath(Name alias, Table<InventoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InventoryPath as(String alias) {
            return new InventoryPath(DSL.name(alias), this);
        }

        @Override
        public InventoryPath as(Name alias) {
            return new InventoryPath(alias, this);
        }

        @Override
        public InventoryPath as(Table<?> alias) {
            return new InventoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.INVENTORY_CHARACTER_ID_IDX, Indexes.INVENTORY_ROOM_ID_IDX);
    }

    @Override
    public UniqueKey<InventoryRecord> getPrimaryKey() {
        return Keys.INVENTORY_PKEY;
    }

    private transient InventoryItemPath _inventoryItem;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.inventory_item</code> table
     */
    public InventoryItemPath inventoryItem() {
        if (_inventoryItem == null)
            _inventoryItem = new InventoryItemPath(this, null, Keys.INVENTORY_ITEM__FKINVENTORY_155964.getInverseKey());

        return _inventoryItem;
    }

    private transient MoneyPath _money;

    /**
     * Get the implicit to-many join path to the <code>itemstorage.money</code>
     * table
     */
    public MoneyPath money() {
        if (_money == null)
            _money = new MoneyPath(this, null, Keys.MONEY__FKMONEY686639.getInverseKey());

        return _money;
    }

    @Override
    public Inventory as(String alias) {
        return new Inventory(DSL.name(alias), this);
    }

    @Override
    public Inventory as(Name alias) {
        return new Inventory(alias, this);
    }

    @Override
    public Inventory as(Table<?> alias) {
        return new Inventory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventory rename(String name) {
        return new Inventory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventory rename(Name name) {
        return new Inventory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Inventory rename(Table<?> name) {
        return new Inventory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory where(Condition condition) {
        return new Inventory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Inventory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Inventory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Inventory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Inventory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Inventory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
