/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItem.InventoryItemPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemSkill.ItemSkillPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.InventoryItemSkillRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryItemSkill extends TableImpl<InventoryItemSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.inventory_item_skill</code>
     */
    public static final InventoryItemSkill INVENTORY_ITEM_SKILL = new InventoryItemSkill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryItemSkillRecord> getRecordType() {
        return InventoryItemSkillRecord.class;
    }

    /**
     * The column <code>itemstorage.inventory_item_skill.id</code>.
     */
    public final TableField<InventoryItemSkillRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>itemstorage.inventory_item_skill.inventory_item_id</code>.
     */
    public final TableField<InventoryItemSkillRecord, UUID> INVENTORY_ITEM_ID = createField(DSL.name("inventory_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item_skill.item_skill_id</code>.
     */
    public final TableField<InventoryItemSkillRecord, UUID> ITEM_SKILL_ID = createField(DSL.name("item_skill_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item_skill.current_charges</code>.
     */
    public final TableField<InventoryItemSkillRecord, Integer> CURRENT_CHARGES = createField(DSL.name("current_charges"), SQLDataType.INTEGER, this, "");

    private InventoryItemSkill(Name alias, Table<InventoryItemSkillRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryItemSkill(Name alias, Table<InventoryItemSkillRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.inventory_item_skill</code> table
     * reference
     */
    public InventoryItemSkill(String alias) {
        this(DSL.name(alias), INVENTORY_ITEM_SKILL);
    }

    /**
     * Create an aliased <code>itemstorage.inventory_item_skill</code> table
     * reference
     */
    public InventoryItemSkill(Name alias) {
        this(alias, INVENTORY_ITEM_SKILL);
    }

    /**
     * Create a <code>itemstorage.inventory_item_skill</code> table reference
     */
    public InventoryItemSkill() {
        this(DSL.name("inventory_item_skill"), null);
    }

    public <O extends Record> InventoryItemSkill(Table<O> path, ForeignKey<O, InventoryItemSkillRecord> childPath, InverseForeignKey<O, InventoryItemSkillRecord> parentPath) {
        super(path, childPath, parentPath, INVENTORY_ITEM_SKILL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InventoryItemSkillPath extends InventoryItemSkill implements Path<InventoryItemSkillRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InventoryItemSkillPath(Table<O> path, ForeignKey<O, InventoryItemSkillRecord> childPath, InverseForeignKey<O, InventoryItemSkillRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InventoryItemSkillPath(Name alias, Table<InventoryItemSkillRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InventoryItemSkillPath as(String alias) {
            return new InventoryItemSkillPath(DSL.name(alias), this);
        }

        @Override
        public InventoryItemSkillPath as(Name alias) {
            return new InventoryItemSkillPath(alias, this);
        }

        @Override
        public InventoryItemSkillPath as(Table<?> alias) {
            return new InventoryItemSkillPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public UniqueKey<InventoryItemSkillRecord> getPrimaryKey() {
        return Keys.INVENTORY_ITEM_SKILL_PKEY;
    }

    @Override
    public List<ForeignKey<InventoryItemSkillRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_170633, Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_355492);
    }

    private transient InventoryItemPath _inventoryItem;

    /**
     * Get the implicit join path to the <code>itemstorage.inventory_item</code>
     * table.
     */
    public InventoryItemPath inventoryItem() {
        if (_inventoryItem == null)
            _inventoryItem = new InventoryItemPath(this, Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_170633, null);

        return _inventoryItem;
    }

    private transient ItemSkillPath _itemSkill;

    /**
     * Get the implicit join path to the <code>itemstorage.item_skill</code>
     * table.
     */
    public ItemSkillPath itemSkill() {
        if (_itemSkill == null)
            _itemSkill = new ItemSkillPath(this, Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_355492, null);

        return _itemSkill;
    }

    @Override
    public InventoryItemSkill as(String alias) {
        return new InventoryItemSkill(DSL.name(alias), this);
    }

    @Override
    public InventoryItemSkill as(Name alias) {
        return new InventoryItemSkill(alias, this);
    }

    @Override
    public InventoryItemSkill as(Table<?> alias) {
        return new InventoryItemSkill(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItemSkill rename(String name) {
        return new InventoryItemSkill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItemSkill rename(Name name) {
        return new InventoryItemSkill(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItemSkill rename(Table<?> name) {
        return new InventoryItemSkill(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill where(Condition condition) {
        return new InventoryItemSkill(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItemSkill where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItemSkill where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItemSkill where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItemSkill where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItemSkill whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
