/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory.InventoryPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItemSkill.InventoryItemSkillPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items.ItemsPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.InventoryItemRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryItem extends TableImpl<InventoryItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.inventory_item</code>
     */
    public static final InventoryItem INVENTORY_ITEM = new InventoryItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryItemRecord> getRecordType() {
        return InventoryItemRecord.class;
    }

    /**
     * The column <code>itemstorage.inventory_item.id</code>.
     */
    public final TableField<InventoryItemRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item.inventory_id</code>.
     */
    public final TableField<InventoryItemRecord, UUID> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item.item_id</code>.
     */
    public final TableField<InventoryItemRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item.count</code>.
     */
    public final TableField<InventoryItemRecord, Long> COUNT = createField(DSL.name("count"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item.in_use</code>.
     */
    public final TableField<InventoryItemRecord, Boolean> IN_USE = createField(DSL.name("in_use"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>itemstorage.inventory_item.attack_bonus_value</code>.
     */
    public final TableField<InventoryItemRecord, Long> ATTACK_BONUS_VALUE = createField(DSL.name("attack_bonus_value"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>itemstorage.inventory_item.damage_bonus_value</code>.
     */
    public final TableField<InventoryItemRecord, Long> DAMAGE_BONUS_VALUE = createField(DSL.name("damage_bonus_value"), SQLDataType.BIGINT, this, "");

    private InventoryItem(Name alias, Table<InventoryItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryItem(Name alias, Table<InventoryItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.inventory_item</code> table reference
     */
    public InventoryItem(String alias) {
        this(DSL.name(alias), INVENTORY_ITEM);
    }

    /**
     * Create an aliased <code>itemstorage.inventory_item</code> table reference
     */
    public InventoryItem(Name alias) {
        this(alias, INVENTORY_ITEM);
    }

    /**
     * Create a <code>itemstorage.inventory_item</code> table reference
     */
    public InventoryItem() {
        this(DSL.name("inventory_item"), null);
    }

    public <O extends Record> InventoryItem(Table<O> path, ForeignKey<O, InventoryItemRecord> childPath, InverseForeignKey<O, InventoryItemRecord> parentPath) {
        super(path, childPath, parentPath, INVENTORY_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InventoryItemPath extends InventoryItem implements Path<InventoryItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InventoryItemPath(Table<O> path, ForeignKey<O, InventoryItemRecord> childPath, InverseForeignKey<O, InventoryItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InventoryItemPath(Name alias, Table<InventoryItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InventoryItemPath as(String alias) {
            return new InventoryItemPath(DSL.name(alias), this);
        }

        @Override
        public InventoryItemPath as(Name alias) {
            return new InventoryItemPath(alias, this);
        }

        @Override
        public InventoryItemPath as(Table<?> alias) {
            return new InventoryItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IN_USE_IDX);
    }

    @Override
    public UniqueKey<InventoryItemRecord> getPrimaryKey() {
        return Keys.INVENTORY_ITEM_PKEY;
    }

    @Override
    public List<ForeignKey<InventoryItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVENTORY_ITEM__FKINVENTORY_155964, Keys.INVENTORY_ITEM__FKINVENTORY_686023);
    }

    private transient InventoryPath _inventory;

    /**
     * Get the implicit join path to the <code>itemstorage.inventory</code>
     * table.
     */
    public InventoryPath inventory() {
        if (_inventory == null)
            _inventory = new InventoryPath(this, Keys.INVENTORY_ITEM__FKINVENTORY_155964, null);

        return _inventory;
    }

    private transient ItemsPath _items;

    /**
     * Get the implicit join path to the <code>itemstorage.items</code> table.
     */
    public ItemsPath items() {
        if (_items == null)
            _items = new ItemsPath(this, Keys.INVENTORY_ITEM__FKINVENTORY_686023, null);

        return _items;
    }

    private transient InventoryItemSkillPath _inventoryItemSkill;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.inventory_item_skill</code> table
     */
    public InventoryItemSkillPath inventoryItemSkill() {
        if (_inventoryItemSkill == null)
            _inventoryItemSkill = new InventoryItemSkillPath(this, null, Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_170633.getInverseKey());

        return _inventoryItemSkill;
    }

    @Override
    public InventoryItem as(String alias) {
        return new InventoryItem(DSL.name(alias), this);
    }

    @Override
    public InventoryItem as(Name alias) {
        return new InventoryItem(alias, this);
    }

    @Override
    public InventoryItem as(Table<?> alias) {
        return new InventoryItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItem rename(String name) {
        return new InventoryItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItem rename(Name name) {
        return new InventoryItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryItem rename(Table<?> name) {
        return new InventoryItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem where(Condition condition) {
        return new InventoryItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
