/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.InventoryItemSkill.InventoryItemSkillPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemSkillRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemSkill extends TableImpl<ItemSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_skill</code>
     */
    public static final ItemSkill ITEM_SKILL = new ItemSkill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemSkillRecord> getRecordType() {
        return ItemSkillRecord.class;
    }

    /**
     * The column <code>itemstorage.item_skill.id</code>.
     */
    public final TableField<ItemSkillRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_skill.item_id</code>.
     */
    public final TableField<ItemSkillRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.item_skill.name</code>.
     */
    public final TableField<ItemSkillRecord, JSONB> NAME = createField(DSL.name("name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_skill.cast_time</code>.
     */
    public final TableField<ItemSkillRecord, String> CAST_TIME = createField(DSL.name("cast_time"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_skill.distance</code>.
     */
    public final TableField<ItemSkillRecord, String> DISTANCE = createField(DSL.name("distance"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_skill.description</code>.
     */
    public final TableField<ItemSkillRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_skill.short_description</code>.
     */
    public final TableField<ItemSkillRecord, String> SHORT_DESCRIPTION = createField(DSL.name("short_description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_skill.charges</code>.
     */
    public final TableField<ItemSkillRecord, Integer> CHARGES = createField(DSL.name("charges"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>itemstorage.item_skill.charges_refill</code>.
     */
    public final TableField<ItemSkillRecord, String> CHARGES_REFILL = createField(DSL.name("charges_refill"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_skill.img_url</code>.
     */
    public final TableField<ItemSkillRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    private ItemSkill(Name alias, Table<ItemSkillRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemSkill(Name alias, Table<ItemSkillRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_skill</code> table reference
     */
    public ItemSkill(String alias) {
        this(DSL.name(alias), ITEM_SKILL);
    }

    /**
     * Create an aliased <code>itemstorage.item_skill</code> table reference
     */
    public ItemSkill(Name alias) {
        this(alias, ITEM_SKILL);
    }

    /**
     * Create a <code>itemstorage.item_skill</code> table reference
     */
    public ItemSkill() {
        this(DSL.name("item_skill"), null);
    }

    public <O extends Record> ItemSkill(Table<O> path, ForeignKey<O, ItemSkillRecord> childPath, InverseForeignKey<O, ItemSkillRecord> parentPath) {
        super(path, childPath, parentPath, ITEM_SKILL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemSkillPath extends ItemSkill implements Path<ItemSkillRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemSkillPath(Table<O> path, ForeignKey<O, ItemSkillRecord> childPath, InverseForeignKey<O, ItemSkillRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemSkillPath(Name alias, Table<ItemSkillRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemSkillPath as(String alias) {
            return new ItemSkillPath(DSL.name(alias), this);
        }

        @Override
        public ItemSkillPath as(Name alias) {
            return new ItemSkillPath(alias, this);
        }

        @Override
        public ItemSkillPath as(Table<?> alias) {
            return new ItemSkillPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public UniqueKey<ItemSkillRecord> getPrimaryKey() {
        return Keys.ITEM_SKILL_PKEY;
    }

    private transient InventoryItemSkillPath _inventoryItemSkill;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.inventory_item_skill</code> table
     */
    public InventoryItemSkillPath inventoryItemSkill() {
        if (_inventoryItemSkill == null)
            _inventoryItemSkill = new InventoryItemSkillPath(this, null, Keys.INVENTORY_ITEM_SKILL__FKINVENTORY_355492.getInverseKey());

        return _inventoryItemSkill;
    }

    @Override
    public ItemSkill as(String alias) {
        return new ItemSkill(DSL.name(alias), this);
    }

    @Override
    public ItemSkill as(Name alias) {
        return new ItemSkill(alias, this);
    }

    @Override
    public ItemSkill as(Table<?> alias) {
        return new ItemSkill(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSkill rename(String name) {
        return new ItemSkill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSkill rename(Name name) {
        return new ItemSkill(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemSkill rename(Table<?> name) {
        return new ItemSkill(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill where(Condition condition) {
        return new ItemSkill(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSkill where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSkill where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSkill where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemSkill where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemSkill whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
