/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.Items.ItemsPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemStatsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemStats extends TableImpl<ItemStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_stats</code>
     */
    public static final ItemStats ITEM_STATS = new ItemStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemStatsRecord> getRecordType() {
        return ItemStatsRecord.class;
    }

    /**
     * The column <code>itemstorage.item_stats.id</code>. Уникальный
     * идентификатор записи
     */
    public final TableField<ItemStatsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "Уникальный идентификатор записи");

    /**
     * The column <code>itemstorage.item_stats.item_id</code>. Уникальный
     * идентификатор предмета
     */
    public final TableField<ItemStatsRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID.nullable(false), this, "Уникальный идентификатор предмета");

    /**
     * The column <code>itemstorage.item_stats.armory_class</code>. Класс брони,
     * даваемый предметом
     */
    public final TableField<ItemStatsRecord, JSONB> ARMORY_CLASS = createField(DSL.name("armory_class"), SQLDataType.JSONB, this, "Класс брони, даваемый предметом");

    /**
     * The column <code>itemstorage.item_stats.speed</code>. Скорость даваемая
     * предметом
     */
    public final TableField<ItemStatsRecord, JSONB> SPEED = createField(DSL.name("speed"), SQLDataType.JSONB, this, "Скорость даваемая предметом");

    /**
     * The column <code>itemstorage.item_stats.hp</code>. ХП даваемое предметом
     */
    public final TableField<ItemStatsRecord, JSONB> HP = createField(DSL.name("hp"), SQLDataType.JSONB, this, "ХП даваемое предметом");

    /**
     * The column <code>itemstorage.item_stats.saving_throw</code>. Спасброски
     * даваемые предметом
     */
    public final TableField<ItemStatsRecord, JSONB> SAVING_THROW = createField(DSL.name("saving_throw"), SQLDataType.JSONB, this, "Спасброски даваемые предметом");

    /**
     * The column <code>itemstorage.item_stats.adventage</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> ADVENTAGE = createField(DSL.name("adventage"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.interference</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> INTERFERENCE = createField(DSL.name("interference"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.resistance</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> RESISTANCE = createField(DSL.name("resistance"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.vulnerability</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> VULNERABILITY = createField(DSL.name("vulnerability"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.immunity</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> IMMUNITY = createField(DSL.name("immunity"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.ability_score</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> ABILITY_SCORE = createField(DSL.name("ability_score"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.proficiency_skill</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> PROFICIENCY_SKILL = createField(DSL.name("proficiency_skill"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.attack_bonus</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> ATTACK_BONUS = createField(DSL.name("attack_bonus"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.damage_bonus</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> DAMAGE_BONUS = createField(DSL.name("damage_bonus"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_stats.limitation</code>.
     */
    public final TableField<ItemStatsRecord, JSONB> LIMITATION = createField(DSL.name("limitation"), SQLDataType.JSONB, this, "");

    private ItemStats(Name alias, Table<ItemStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemStats(Name alias, Table<ItemStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_stats</code> table reference
     */
    public ItemStats(String alias) {
        this(DSL.name(alias), ITEM_STATS);
    }

    /**
     * Create an aliased <code>itemstorage.item_stats</code> table reference
     */
    public ItemStats(Name alias) {
        this(alias, ITEM_STATS);
    }

    /**
     * Create a <code>itemstorage.item_stats</code> table reference
     */
    public ItemStats() {
        this(DSL.name("item_stats"), null);
    }

    public <O extends Record> ItemStats(Table<O> path, ForeignKey<O, ItemStatsRecord> childPath, InverseForeignKey<O, ItemStatsRecord> parentPath) {
        super(path, childPath, parentPath, ITEM_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemStatsPath extends ItemStats implements Path<ItemStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemStatsPath(Table<O> path, ForeignKey<O, ItemStatsRecord> childPath, InverseForeignKey<O, ItemStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemStatsPath(Name alias, Table<ItemStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemStatsPath as(String alias) {
            return new ItemStatsPath(DSL.name(alias), this);
        }

        @Override
        public ItemStatsPath as(Name alias) {
            return new ItemStatsPath(alias, this);
        }

        @Override
        public ItemStatsPath as(Table<?> alias) {
            return new ItemStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEM_STATS_ITEM_ID_IDX);
    }

    @Override
    public UniqueKey<ItemStatsRecord> getPrimaryKey() {
        return Keys.ITEM_STATS_PK;
    }

    @Override
    public List<ForeignKey<ItemStatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEM_STATS__ITEM_STATS_ITEMS_FK);
    }

    private transient ItemsPath _items;

    /**
     * Get the implicit join path to the <code>itemstorage.items</code> table.
     */
    public ItemsPath items() {
        if (_items == null)
            _items = new ItemsPath(this, Keys.ITEM_STATS__ITEM_STATS_ITEMS_FK, null);

        return _items;
    }

    @Override
    public ItemStats as(String alias) {
        return new ItemStats(DSL.name(alias), this);
    }

    @Override
    public ItemStats as(Name alias) {
        return new ItemStats(alias, this);
    }

    @Override
    public ItemStats as(Table<?> alias) {
        return new ItemStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemStats rename(String name) {
        return new ItemStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemStats rename(Name name) {
        return new ItemStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemStats rename(Table<?> name) {
        return new ItemStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats where(Condition condition) {
        return new ItemStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
