/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.BundlePurchase.BundlePurchasePath;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundled.ItemBundledPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.RoomBundle.RoomBundlePath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemBundleRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemBundle extends TableImpl<ItemBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_bundle</code>
     */
    public static final ItemBundle ITEM_BUNDLE = new ItemBundle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemBundleRecord> getRecordType() {
        return ItemBundleRecord.class;
    }

    /**
     * The column <code>itemstorage.item_bundle.id</code>.
     */
    public final TableField<ItemBundleRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundle.name</code>.
     */
    public final TableField<ItemBundleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundle.description</code>.
     */
    public final TableField<ItemBundleRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundle.created_at</code>.
     */
    public final TableField<ItemBundleRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundle.img_url</code>.
     */
    public final TableField<ItemBundleRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundle.owner_user_id</code>.
     */
    public final TableField<ItemBundleRecord, UUID> OWNER_USER_ID = createField(DSL.name("owner_user_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.item_bundle.is_public</code>.
     */
    public final TableField<ItemBundleRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.item_bundle.price_crystals</code>.
     */
    public final TableField<ItemBundleRecord, Integer> PRICE_CRYSTALS = createField(DSL.name("price_crystals"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private ItemBundle(Name alias, Table<ItemBundleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemBundle(Name alias, Table<ItemBundleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_bundle</code> table reference
     */
    public ItemBundle(String alias) {
        this(DSL.name(alias), ITEM_BUNDLE);
    }

    /**
     * Create an aliased <code>itemstorage.item_bundle</code> table reference
     */
    public ItemBundle(Name alias) {
        this(alias, ITEM_BUNDLE);
    }

    /**
     * Create a <code>itemstorage.item_bundle</code> table reference
     */
    public ItemBundle() {
        this(DSL.name("item_bundle"), null);
    }

    public <O extends Record> ItemBundle(Table<O> path, ForeignKey<O, ItemBundleRecord> childPath, InverseForeignKey<O, ItemBundleRecord> parentPath) {
        super(path, childPath, parentPath, ITEM_BUNDLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemBundlePath extends ItemBundle implements Path<ItemBundleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemBundlePath(Table<O> path, ForeignKey<O, ItemBundleRecord> childPath, InverseForeignKey<O, ItemBundleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemBundlePath(Name alias, Table<ItemBundleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemBundlePath as(String alias) {
            return new ItemBundlePath(DSL.name(alias), this);
        }

        @Override
        public ItemBundlePath as(Name alias) {
            return new ItemBundlePath(alias, this);
        }

        @Override
        public ItemBundlePath as(Table<?> alias) {
            return new ItemBundlePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public UniqueKey<ItemBundleRecord> getPrimaryKey() {
        return Keys.ITEM_BUNDLE_PKEY;
    }

    private transient BundlePurchasePath _bundlePurchase;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.bundle_purchase</code> table
     */
    public BundlePurchasePath bundlePurchase() {
        if (_bundlePurchase == null)
            _bundlePurchase = new BundlePurchasePath(this, null, Keys.BUNDLE_PURCHASE__FK_BUNDLE_PURCHASE_BUNDLE.getInverseKey());

        return _bundlePurchase;
    }

    private transient ItemBundledPath _itemBundled;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.item_bundled</code> table
     */
    public ItemBundledPath itemBundled() {
        if (_itemBundled == null)
            _itemBundled = new ItemBundledPath(this, null, Keys.ITEM_BUNDLED__FKITEM_BUNDL939553.getInverseKey());

        return _itemBundled;
    }

    private transient RoomBundlePath _roomBundle;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.room_bundle</code> table
     */
    public RoomBundlePath roomBundle() {
        if (_roomBundle == null)
            _roomBundle = new RoomBundlePath(this, null, Keys.ROOM_BUNDLE__FKROOM_BUNDL902626.getInverseKey());

        return _roomBundle;
    }

    @Override
    public ItemBundle as(String alias) {
        return new ItemBundle(DSL.name(alias), this);
    }

    @Override
    public ItemBundle as(Name alias) {
        return new ItemBundle(alias, this);
    }

    @Override
    public ItemBundle as(Table<?> alias) {
        return new ItemBundle(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundle rename(String name) {
        return new ItemBundle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundle rename(Name name) {
        return new ItemBundle(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundle rename(Table<?> name) {
        return new ItemBundle(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle where(Condition condition) {
        return new ItemBundle(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundle where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundle where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundle where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundle where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundle whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
