/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemStats.ItemStatsPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Items extends TableImpl<ItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.items</code>
     */
    public static final Items ITEMS = new Items();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemsRecord> getRecordType() {
        return ItemsRecord.class;
    }

    /**
     * The column <code>itemstorage.items.id</code>.
     */
    public final TableField<ItemsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items.name</code>.
     */
    public final TableField<ItemsRecord, JSONB> NAME = createField(DSL.name("name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items.type</code>.
     */
    public final TableField<ItemsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items.subtype</code>.
     */
    public final TableField<ItemsRecord, String> SUBTYPE = createField(DSL.name("subtype"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items.customization</code>.
     */
    public final TableField<ItemsRecord, Boolean> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>itemstorage.items.rarity</code>.
     */
    public final TableField<ItemsRecord, String> RARITY = createField(DSL.name("rarity"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items.description</code>.
     */
    public final TableField<ItemsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items.stats</code>.
     */
    public final TableField<ItemsRecord, JSONB> STATS = createField(DSL.name("stats"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.items.created_at</code>.
     */
    public final TableField<ItemsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>itemstorage.items.room_id</code>.
     */
    public final TableField<ItemsRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items.creator_id</code>.
     */
    public final TableField<ItemsRecord, UUID> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items.img_url</code>.
     */
    public final TableField<ItemsRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items.visible_for_players</code>.
     */
    public final TableField<ItemsRecord, Boolean> VISIBLE_FOR_PLAYERS = createField(DSL.name("visible_for_players"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.items.creator</code>.
     */
    public final TableField<ItemsRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items.description_eng</code>.
     */
    public final TableField<ItemsRecord, String> DESCRIPTION_ENG = createField(DSL.name("description_eng"), SQLDataType.CLOB, this, "");

    private Items(Name alias, Table<ItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Items(Name alias, Table<ItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.items</code> table reference
     */
    public Items(String alias) {
        this(DSL.name(alias), ITEMS);
    }

    /**
     * Create an aliased <code>itemstorage.items</code> table reference
     */
    public Items(Name alias) {
        this(alias, ITEMS);
    }

    /**
     * Create a <code>itemstorage.items</code> table reference
     */
    public Items() {
        this(DSL.name("items"), null);
    }

    public <O extends Record> Items(Table<O> path, ForeignKey<O, ItemsRecord> childPath, InverseForeignKey<O, ItemsRecord> parentPath) {
        super(path, childPath, parentPath, ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemsPath extends Items implements Path<ItemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemsPath(Table<O> path, ForeignKey<O, ItemsRecord> childPath, InverseForeignKey<O, ItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemsPath(Name alias, Table<ItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemsPath as(String alias) {
            return new ItemsPath(DSL.name(alias), this);
        }

        @Override
        public ItemsPath as(Name alias) {
            return new ItemsPath(alias, this);
        }

        @Override
        public ItemsPath as(Table<?> alias) {
            return new ItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEMS_TYPE_IDX);
    }

    @Override
    public UniqueKey<ItemsRecord> getPrimaryKey() {
        return Keys.ITEMS_PKEY;
    }

    private transient ItemStatsPath _itemStats;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.item_stats</code> table
     */
    public ItemStatsPath itemStats() {
        if (_itemStats == null)
            _itemStats = new ItemStatsPath(this, null, Keys.ITEM_STATS__ITEM_STATS_ITEMS_FK.getInverseKey());

        return _itemStats;
    }

    @Override
    public Items as(String alias) {
        return new Items(DSL.name(alias), this);
    }

    @Override
    public Items as(Name alias) {
        return new Items(alias, this);
    }

    @Override
    public Items as(Table<?> alias) {
        return new Items(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(String name) {
        return new Items(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(Name name) {
        return new Items(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items rename(Table<?> name) {
        return new Items(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items where(Condition condition) {
        return new Items(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
