/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemTagRelationRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemTagRelation extends TableImpl<ItemTagRelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_tag_relation</code>
     */
    public static final ItemTagRelation ITEM_TAG_RELATION = new ItemTagRelation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemTagRelationRecord> getRecordType() {
        return ItemTagRelationRecord.class;
    }

    /**
     * The column <code>itemstorage.item_tag_relation.item_id</code>.
     */
    public final TableField<ItemTagRelationRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_tag_relation.tag_id</code>.
     */
    public final TableField<ItemTagRelationRecord, UUID> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.UUID.nullable(false), this, "");

    private ItemTagRelation(Name alias, Table<ItemTagRelationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemTagRelation(Name alias, Table<ItemTagRelationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_tag_relation</code> table
     * reference
     */
    public ItemTagRelation(String alias) {
        this(DSL.name(alias), ITEM_TAG_RELATION);
    }

    /**
     * Create an aliased <code>itemstorage.item_tag_relation</code> table
     * reference
     */
    public ItemTagRelation(Name alias) {
        this(alias, ITEM_TAG_RELATION);
    }

    /**
     * Create a <code>itemstorage.item_tag_relation</code> table reference
     */
    public ItemTagRelation() {
        this(DSL.name("item_tag_relation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ITEM_TAG_RELATION_TAG_ID);
    }

    @Override
    public UniqueKey<ItemTagRelationRecord> getPrimaryKey() {
        return Keys.PK_ITEM_TAG_RELATION;
    }

    @Override
    public ItemTagRelation as(String alias) {
        return new ItemTagRelation(DSL.name(alias), this);
    }

    @Override
    public ItemTagRelation as(Name alias) {
        return new ItemTagRelation(alias, this);
    }

    @Override
    public ItemTagRelation as(Table<?> alias) {
        return new ItemTagRelation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTagRelation rename(String name) {
        return new ItemTagRelation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTagRelation rename(Name name) {
        return new ItemTagRelation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTagRelation rename(Table<?> name) {
        return new ItemTagRelation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation where(Condition condition) {
        return new ItemTagRelation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTagRelation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTagRelation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTagRelation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTagRelation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTagRelation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
