/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemTagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemTag extends TableImpl<ItemTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_tag</code>
     */
    public static final ItemTag ITEM_TAG = new ItemTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemTagRecord> getRecordType() {
        return ItemTagRecord.class;
    }

    /**
     * The column <code>itemstorage.item_tag.id</code>.
     */
    public final TableField<ItemTagRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>itemstorage.item_tag.name</code>.
     */
    public final TableField<ItemTagRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_tag.description</code>.
     */
    public final TableField<ItemTagRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_tag.room_id</code>.
     */
    public final TableField<ItemTagRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID, this, "");

    private ItemTag(Name alias, Table<ItemTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemTag(Name alias, Table<ItemTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_tag</code> table reference
     */
    public ItemTag(String alias) {
        this(DSL.name(alias), ITEM_TAG);
    }

    /**
     * Create an aliased <code>itemstorage.item_tag</code> table reference
     */
    public ItemTag(Name alias) {
        this(alias, ITEM_TAG);
    }

    /**
     * Create a <code>itemstorage.item_tag</code> table reference
     */
    public ItemTag() {
        this(DSL.name("item_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ITEM_TAG_ROOM_ID);
    }

    @Override
    public UniqueKey<ItemTagRecord> getPrimaryKey() {
        return Keys.PK_ITEM_TAG;
    }

    @Override
    public List<UniqueKey<ItemTagRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_ITEM_TAG_NAME_ROOM);
    }

    @Override
    public ItemTag as(String alias) {
        return new ItemTag(DSL.name(alias), this);
    }

    @Override
    public ItemTag as(Name alias) {
        return new ItemTag(alias, this);
    }

    @Override
    public ItemTag as(Table<?> alias) {
        return new ItemTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTag rename(String name) {
        return new ItemTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTag rename(Name name) {
        return new ItemTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemTag rename(Table<?> name) {
        return new ItemTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag where(Condition condition) {
        return new ItemTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
