/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemsUser.ItemsUserPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemsUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemsUser extends TableImpl<ItemsUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.items_user</code>
     */
    public static final ItemsUser ITEMS_USER = new ItemsUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemsUserRecord> getRecordType() {
        return ItemsUserRecord.class;
    }

    /**
     * The column <code>itemstorage.items_user.id</code>.
     */
    public final TableField<ItemsUserRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_user.name</code>.
     */
    public final TableField<ItemsUserRecord, JSONB> NAME = createField(DSL.name("name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_user.type</code>.
     */
    public final TableField<ItemsUserRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_user.subtype</code>.
     */
    public final TableField<ItemsUserRecord, String> SUBTYPE = createField(DSL.name("subtype"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.customization</code>.
     */
    public final TableField<ItemsUserRecord, Boolean> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>itemstorage.items_user.rarity</code>.
     */
    public final TableField<ItemsUserRecord, String> RARITY = createField(DSL.name("rarity"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.description</code>.
     */
    public final TableField<ItemsUserRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.stats</code>.
     */
    public final TableField<ItemsUserRecord, JSONB> STATS = createField(DSL.name("stats"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.items_user.created_at</code>.
     */
    public final TableField<ItemsUserRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_user.room_id</code>.
     */
    public final TableField<ItemsUserRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items_user.creator_id</code>.
     */
    public final TableField<ItemsUserRecord, UUID> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items_user.img_url</code>.
     */
    public final TableField<ItemsUserRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.visible_for_players</code>.
     */
    public final TableField<ItemsUserRecord, Boolean> VISIBLE_FOR_PLAYERS = createField(DSL.name("visible_for_players"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.items_user.creator</code>.
     */
    public final TableField<ItemsUserRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.description_eng</code>.
     */
    public final TableField<ItemsUserRecord, String> DESCRIPTION_ENG = createField(DSL.name("description_eng"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_user.hidden_stats</code>.
     */
    public final TableField<ItemsUserRecord, Boolean> HIDDEN_STATS = createField(DSL.name("hidden_stats"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.items_user.unidentified_item_id</code>.
     */
    public final TableField<ItemsUserRecord, UUID> UNIDENTIFIED_ITEM_ID = createField(DSL.name("unidentified_item_id"), SQLDataType.UUID, this, "");

    private ItemsUser(Name alias, Table<ItemsUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemsUser(Name alias, Table<ItemsUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.items_user</code> table reference
     */
    public ItemsUser(String alias) {
        this(DSL.name(alias), ITEMS_USER);
    }

    /**
     * Create an aliased <code>itemstorage.items_user</code> table reference
     */
    public ItemsUser(Name alias) {
        this(alias, ITEMS_USER);
    }

    /**
     * Create a <code>itemstorage.items_user</code> table reference
     */
    public ItemsUser() {
        this(DSL.name("items_user"), null);
    }

    public <O extends Record> ItemsUser(Table<O> path, ForeignKey<O, ItemsUserRecord> childPath, InverseForeignKey<O, ItemsUserRecord> parentPath) {
        super(path, childPath, parentPath, ITEMS_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemsUserPath extends ItemsUser implements Path<ItemsUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemsUserPath(Table<O> path, ForeignKey<O, ItemsUserRecord> childPath, InverseForeignKey<O, ItemsUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemsUserPath(Name alias, Table<ItemsUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemsUserPath as(String alias) {
            return new ItemsUserPath(DSL.name(alias), this);
        }

        @Override
        public ItemsUserPath as(Name alias) {
            return new ItemsUserPath(alias, this);
        }

        @Override
        public ItemsUserPath as(Table<?> alias) {
            return new ItemsUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEMS_USER_TYPE_IDX);
    }

    @Override
    public UniqueKey<ItemsUserRecord> getPrimaryKey() {
        return Keys.ITEMS_USER_PKEY;
    }

    @Override
    public List<ForeignKey<ItemsUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEMS_USER__ITEMS_USER_UNIDENTIFIED_ITEM_ID_FKEY);
    }

    private transient ItemsUserPath _itemsUser;

    /**
     * Get the implicit join path to the <code>itemstorage.items_user</code>
     * table.
     */
    public ItemsUserPath itemsUser() {
        if (_itemsUser == null)
            _itemsUser = new ItemsUserPath(this, Keys.ITEMS_USER__ITEMS_USER_UNIDENTIFIED_ITEM_ID_FKEY, null);

        return _itemsUser;
    }

    @Override
    public ItemsUser as(String alias) {
        return new ItemsUser(DSL.name(alias), this);
    }

    @Override
    public ItemsUser as(Name alias) {
        return new ItemsUser(alias, this);
    }

    @Override
    public ItemsUser as(Table<?> alias) {
        return new ItemsUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemsUser rename(String name) {
        return new ItemsUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemsUser rename(Name name) {
        return new ItemsUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemsUser rename(Table<?> name) {
        return new ItemsUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser where(Condition condition) {
        return new ItemsUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemsUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemsUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemsUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemsUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemsUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
