/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle.ItemBundlePath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ItemBundledRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemBundled extends TableImpl<ItemBundledRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.item_bundled</code>
     */
    public static final ItemBundled ITEM_BUNDLED = new ItemBundled();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemBundledRecord> getRecordType() {
        return ItemBundledRecord.class;
    }

    /**
     * The column <code>itemstorage.item_bundled.id</code>.
     */
    public final TableField<ItemBundledRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundled.item_bundle_id</code>.
     */
    public final TableField<ItemBundledRecord, UUID> ITEM_BUNDLE_ID = createField(DSL.name("item_bundle_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundled.name</code>.
     */
    public final TableField<ItemBundledRecord, JSONB> NAME = createField(DSL.name("name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundled.type</code>.
     */
    public final TableField<ItemBundledRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundled.subtype</code>.
     */
    public final TableField<ItemBundledRecord, String> SUBTYPE = createField(DSL.name("subtype"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.customization</code>.
     */
    public final TableField<ItemBundledRecord, Boolean> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>itemstorage.item_bundled.rarity</code>.
     */
    public final TableField<ItemBundledRecord, String> RARITY = createField(DSL.name("rarity"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.description</code>.
     */
    public final TableField<ItemBundledRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.stats</code>.
     */
    public final TableField<ItemBundledRecord, JSONB> STATS = createField(DSL.name("stats"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.created_at</code>.
     */
    public final TableField<ItemBundledRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>itemstorage.item_bundled.creator_id</code>.
     */
    public final TableField<ItemBundledRecord, UUID> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.item_bundled.img_url</code>.
     */
    public final TableField<ItemBundledRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.visible_for_players</code>.
     */
    public final TableField<ItemBundledRecord, Boolean> VISIBLE_FOR_PLAYERS = createField(DSL.name("visible_for_players"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>itemstorage.item_bundled.creator</code>.
     */
    public final TableField<ItemBundledRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.description_eng</code>.
     */
    public final TableField<ItemBundledRecord, String> DESCRIPTION_ENG = createField(DSL.name("description_eng"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.item_bundled.historical</code>.
     */
    public final TableField<ItemBundledRecord, Boolean> HISTORICAL = createField(DSL.name("historical"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.item_bundled.hidden_stats</code>.
     */
    public final TableField<ItemBundledRecord, Boolean> HIDDEN_STATS = createField(DSL.name("hidden_stats"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.item_bundled.unidentified_item_id</code>.
     */
    public final TableField<ItemBundledRecord, UUID> UNIDENTIFIED_ITEM_ID = createField(DSL.name("unidentified_item_id"), SQLDataType.UUID, this, "");

    private ItemBundled(Name alias, Table<ItemBundledRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemBundled(Name alias, Table<ItemBundledRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.item_bundled</code> table reference
     */
    public ItemBundled(String alias) {
        this(DSL.name(alias), ITEM_BUNDLED);
    }

    /**
     * Create an aliased <code>itemstorage.item_bundled</code> table reference
     */
    public ItemBundled(Name alias) {
        this(alias, ITEM_BUNDLED);
    }

    /**
     * Create a <code>itemstorage.item_bundled</code> table reference
     */
    public ItemBundled() {
        this(DSL.name("item_bundled"), null);
    }

    public <O extends Record> ItemBundled(Table<O> path, ForeignKey<O, ItemBundledRecord> childPath, InverseForeignKey<O, ItemBundledRecord> parentPath) {
        super(path, childPath, parentPath, ITEM_BUNDLED);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemBundledPath extends ItemBundled implements Path<ItemBundledRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemBundledPath(Table<O> path, ForeignKey<O, ItemBundledRecord> childPath, InverseForeignKey<O, ItemBundledRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemBundledPath(Name alias, Table<ItemBundledRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemBundledPath as(String alias) {
            return new ItemBundledPath(DSL.name(alias), this);
        }

        @Override
        public ItemBundledPath as(Name alias) {
            return new ItemBundledPath(alias, this);
        }

        @Override
        public ItemBundledPath as(Table<?> alias) {
            return new ItemBundledPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public UniqueKey<ItemBundledRecord> getPrimaryKey() {
        return Keys.ITEM_BUNDLED_PKEY;
    }

    @Override
    public List<ForeignKey<ItemBundledRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEM_BUNDLED__FKITEM_BUNDL939553);
    }

    private transient ItemBundlePath _itemBundle;

    /**
     * Get the implicit join path to the <code>itemstorage.item_bundle</code>
     * table.
     */
    public ItemBundlePath itemBundle() {
        if (_itemBundle == null)
            _itemBundle = new ItemBundlePath(this, Keys.ITEM_BUNDLED__FKITEM_BUNDL939553, null);

        return _itemBundle;
    }

    @Override
    public ItemBundled as(String alias) {
        return new ItemBundled(DSL.name(alias), this);
    }

    @Override
    public ItemBundled as(Name alias) {
        return new ItemBundled(alias, this);
    }

    @Override
    public ItemBundled as(Table<?> alias) {
        return new ItemBundled(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundled rename(String name) {
        return new ItemBundled(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundled rename(Name name) {
        return new ItemBundled(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemBundled rename(Table<?> name) {
        return new ItemBundled(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled where(Condition condition) {
        return new ItemBundled(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundled where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundled where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundled where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemBundled where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemBundled whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
