/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.Items_24Record;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Items_24 extends TableImpl<Items_24Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.items_24</code>
     */
    public static final Items_24 ITEMS_24 = new Items_24();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Items_24Record> getRecordType() {
        return Items_24Record.class;
    }

    /**
     * The column <code>itemstorage.items_24.id</code>.
     */
    public final TableField<Items_24Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_24.name</code>.
     */
    public final TableField<Items_24Record, JSONB> NAME = createField(DSL.name("name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_24.type</code>.
     */
    public final TableField<Items_24Record, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_24.subtype</code>.
     */
    public final TableField<Items_24Record, String> SUBTYPE = createField(DSL.name("subtype"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.customization</code>.
     */
    public final TableField<Items_24Record, Boolean> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>itemstorage.items_24.rarity</code>.
     */
    public final TableField<Items_24Record, String> RARITY = createField(DSL.name("rarity"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.description</code>.
     */
    public final TableField<Items_24Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.stats</code>.
     */
    public final TableField<Items_24Record, JSONB> STATS = createField(DSL.name("stats"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>itemstorage.items_24.created_at</code>.
     */
    public final TableField<Items_24Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>itemstorage.items_24.room_id</code>.
     */
    public final TableField<Items_24Record, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items_24.creator_id</code>.
     */
    public final TableField<Items_24Record, UUID> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.items_24.img_url</code>.
     */
    public final TableField<Items_24Record, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.visible_for_players</code>.
     */
    public final TableField<Items_24Record, Boolean> VISIBLE_FOR_PLAYERS = createField(DSL.name("visible_for_players"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>itemstorage.items_24.creator</code>.
     */
    public final TableField<Items_24Record, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.description_eng</code>.
     */
    public final TableField<Items_24Record, String> DESCRIPTION_ENG = createField(DSL.name("description_eng"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.items_24.source</code>.
     */
    public final TableField<Items_24Record, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB, this, "");

    private Items_24(Name alias, Table<Items_24Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Items_24(Name alias, Table<Items_24Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.items_24</code> table reference
     */
    public Items_24(String alias) {
        this(DSL.name(alias), ITEMS_24);
    }

    /**
     * Create an aliased <code>itemstorage.items_24</code> table reference
     */
    public Items_24(Name alias) {
        this(alias, ITEMS_24);
    }

    /**
     * Create a <code>itemstorage.items_24</code> table reference
     */
    public Items_24() {
        this(DSL.name("items_24"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEMS_24_TYPE_IDX);
    }

    @Override
    public UniqueKey<Items_24Record> getPrimaryKey() {
        return Keys.ITEMS_24_PKEY;
    }

    @Override
    public Items_24 as(String alias) {
        return new Items_24(DSL.name(alias), this);
    }

    @Override
    public Items_24 as(Name alias) {
        return new Items_24(alias, this);
    }

    @Override
    public Items_24 as(Table<?> alias) {
        return new Items_24(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Items_24 rename(String name) {
        return new Items_24(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items_24 rename(Name name) {
        return new Items_24(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Items_24 rename(Table<?> name) {
        return new Items_24(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 where(Condition condition) {
        return new Items_24(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items_24 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items_24 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items_24 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Items_24 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Items_24 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
