/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.Inventory.InventoryPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.MoneyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Money extends TableImpl<MoneyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.money</code>
     */
    public static final Money MONEY = new Money();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoneyRecord> getRecordType() {
        return MoneyRecord.class;
    }

    /**
     * The column <code>itemstorage.money.id</code>.
     */
    public final TableField<MoneyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.money.inventory_id</code>.
     */
    public final TableField<MoneyRecord, UUID> INVENTORY_ID = createField(DSL.name("inventory_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.money.golden_count</code>.
     */
    public final TableField<MoneyRecord, Long> GOLDEN_COUNT = createField(DSL.name("golden_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.money.silver_count</code>.
     */
    public final TableField<MoneyRecord, Long> SILVER_COUNT = createField(DSL.name("silver_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.money.copper_count</code>.
     */
    public final TableField<MoneyRecord, Long> COPPER_COUNT = createField(DSL.name("copper_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.money.electrum_count</code>.
     */
    public final TableField<MoneyRecord, Long> ELECTRUM_COUNT = createField(DSL.name("electrum_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.money.platinum_count</code>.
     */
    public final TableField<MoneyRecord, Long> PLATINUM_COUNT = createField(DSL.name("platinum_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private Money(Name alias, Table<MoneyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Money(Name alias, Table<MoneyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.money</code> table reference
     */
    public Money(String alias) {
        this(DSL.name(alias), MONEY);
    }

    /**
     * Create an aliased <code>itemstorage.money</code> table reference
     */
    public Money(Name alias) {
        this(alias, MONEY);
    }

    /**
     * Create a <code>itemstorage.money</code> table reference
     */
    public Money() {
        this(DSL.name("money"), null);
    }

    public <O extends Record> Money(Table<O> path, ForeignKey<O, MoneyRecord> childPath, InverseForeignKey<O, MoneyRecord> parentPath) {
        super(path, childPath, parentPath, MONEY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MoneyPath extends Money implements Path<MoneyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MoneyPath(Table<O> path, ForeignKey<O, MoneyRecord> childPath, InverseForeignKey<O, MoneyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MoneyPath(Name alias, Table<MoneyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MoneyPath as(String alias) {
            return new MoneyPath(DSL.name(alias), this);
        }

        @Override
        public MoneyPath as(Name alias) {
            return new MoneyPath(alias, this);
        }

        @Override
        public MoneyPath as(Table<?> alias) {
            return new MoneyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MONEY_INVENTORY_ID);
    }

    @Override
    public UniqueKey<MoneyRecord> getPrimaryKey() {
        return Keys.MONEY_PKEY;
    }

    @Override
    public List<ForeignKey<MoneyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MONEY__FKMONEY686639);
    }

    private transient InventoryPath _inventory;

    /**
     * Get the implicit join path to the <code>itemstorage.inventory</code>
     * table.
     */
    public InventoryPath inventory() {
        if (_inventory == null)
            _inventory = new InventoryPath(this, Keys.MONEY__FKMONEY686639, null);

        return _inventory;
    }

    @Override
    public Money as(String alias) {
        return new Money(DSL.name(alias), this);
    }

    @Override
    public Money as(Name alias) {
        return new Money(alias, this);
    }

    @Override
    public Money as(Table<?> alias) {
        return new Money(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Money rename(String name) {
        return new Money(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Money rename(Name name) {
        return new Money(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Money rename(Table<?> name) {
        return new Money(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money where(Condition condition) {
        return new Money(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Money where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Money where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Money where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Money where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Money whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
