/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ItemBundle.ItemBundlePath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.RoomBundleRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomBundle extends TableImpl<RoomBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.room_bundle</code>
     */
    public static final RoomBundle ROOM_BUNDLE = new RoomBundle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomBundleRecord> getRecordType() {
        return RoomBundleRecord.class;
    }

    /**
     * The column <code>itemstorage.room_bundle.id</code>.
     */
    public final TableField<RoomBundleRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.room_bundle.room_id</code>.
     */
    public final TableField<RoomBundleRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.room_bundle.item_bundle_id</code>.
     */
    public final TableField<RoomBundleRecord, UUID> ITEM_BUNDLE_ID = createField(DSL.name("item_bundle_id"), SQLDataType.UUID.nullable(false), this, "");

    private RoomBundle(Name alias, Table<RoomBundleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoomBundle(Name alias, Table<RoomBundleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.room_bundle</code> table reference
     */
    public RoomBundle(String alias) {
        this(DSL.name(alias), ROOM_BUNDLE);
    }

    /**
     * Create an aliased <code>itemstorage.room_bundle</code> table reference
     */
    public RoomBundle(Name alias) {
        this(alias, ROOM_BUNDLE);
    }

    /**
     * Create a <code>itemstorage.room_bundle</code> table reference
     */
    public RoomBundle() {
        this(DSL.name("room_bundle"), null);
    }

    public <O extends Record> RoomBundle(Table<O> path, ForeignKey<O, RoomBundleRecord> childPath, InverseForeignKey<O, RoomBundleRecord> parentPath) {
        super(path, childPath, parentPath, ROOM_BUNDLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoomBundlePath extends RoomBundle implements Path<RoomBundleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoomBundlePath(Table<O> path, ForeignKey<O, RoomBundleRecord> childPath, InverseForeignKey<O, RoomBundleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoomBundlePath(Name alias, Table<RoomBundleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoomBundlePath as(String alias) {
            return new RoomBundlePath(DSL.name(alias), this);
        }

        @Override
        public RoomBundlePath as(Name alias) {
            return new RoomBundlePath(alias, this);
        }

        @Override
        public RoomBundlePath as(Table<?> alias) {
            return new RoomBundlePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROOM_BUNDLE_ROOM_ID);
    }

    @Override
    public UniqueKey<RoomBundleRecord> getPrimaryKey() {
        return Keys.ROOM_BUNDLE_PKEY;
    }

    @Override
    public List<ForeignKey<RoomBundleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROOM_BUNDLE__FKROOM_BUNDL902626);
    }

    private transient ItemBundlePath _itemBundle;

    /**
     * Get the implicit join path to the <code>itemstorage.item_bundle</code>
     * table.
     */
    public ItemBundlePath itemBundle() {
        if (_itemBundle == null)
            _itemBundle = new ItemBundlePath(this, Keys.ROOM_BUNDLE__FKROOM_BUNDL902626, null);

        return _itemBundle;
    }

    @Override
    public RoomBundle as(String alias) {
        return new RoomBundle(DSL.name(alias), this);
    }

    @Override
    public RoomBundle as(Name alias) {
        return new RoomBundle(alias, this);
    }

    @Override
    public RoomBundle as(Table<?> alias) {
        return new RoomBundle(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomBundle rename(String name) {
        return new RoomBundle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomBundle rename(Name name) {
        return new RoomBundle(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomBundle rename(Table<?> name) {
        return new RoomBundle(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle where(Condition condition) {
        return new RoomBundle(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomBundle where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomBundle where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomBundle where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomBundle where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomBundle whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
