/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.Shop.ShopPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ShopItemRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShopItem extends TableImpl<ShopItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.shop_item</code>
     */
    public static final ShopItem SHOP_ITEM = new ShopItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopItemRecord> getRecordType() {
        return ShopItemRecord.class;
    }

    /**
     * The column <code>itemstorage.shop_item.id</code>.
     */
    public final TableField<ShopItemRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop_item.shop_id</code>.
     */
    public final TableField<ShopItemRecord, UUID> SHOP_ID = createField(DSL.name("shop_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop_item.item_id</code>.
     */
    public final TableField<ShopItemRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop_item.price_gold</code>.
     */
    public final TableField<ShopItemRecord, Long> PRICE_GOLD = createField(DSL.name("price_gold"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.shop_item.price_silver</code>.
     */
    public final TableField<ShopItemRecord, Long> PRICE_SILVER = createField(DSL.name("price_silver"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.shop_item.price_copper</code>.
     */
    public final TableField<ShopItemRecord, Long> PRICE_COPPER = createField(DSL.name("price_copper"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>itemstorage.shop_item.sort_order</code>.
     */
    public final TableField<ShopItemRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>itemstorage.shop_item.created_at</code>.
     */
    public final TableField<ShopItemRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ShopItem(Name alias, Table<ShopItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShopItem(Name alias, Table<ShopItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.shop_item</code> table reference
     */
    public ShopItem(String alias) {
        this(DSL.name(alias), SHOP_ITEM);
    }

    /**
     * Create an aliased <code>itemstorage.shop_item</code> table reference
     */
    public ShopItem(Name alias) {
        this(alias, SHOP_ITEM);
    }

    /**
     * Create a <code>itemstorage.shop_item</code> table reference
     */
    public ShopItem() {
        this(DSL.name("shop_item"), null);
    }

    public <O extends Record> ShopItem(Table<O> path, ForeignKey<O, ShopItemRecord> childPath, InverseForeignKey<O, ShopItemRecord> parentPath) {
        super(path, childPath, parentPath, SHOP_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShopItemPath extends ShopItem implements Path<ShopItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShopItemPath(Table<O> path, ForeignKey<O, ShopItemRecord> childPath, InverseForeignKey<O, ShopItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShopItemPath(Name alias, Table<ShopItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShopItemPath as(String alias) {
            return new ShopItemPath(DSL.name(alias), this);
        }

        @Override
        public ShopItemPath as(Name alias) {
            return new ShopItemPath(alias, this);
        }

        @Override
        public ShopItemPath as(Table<?> alias) {
            return new ShopItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHOP_ITEM_SHOP_ID_IDX);
    }

    @Override
    public UniqueKey<ShopItemRecord> getPrimaryKey() {
        return Keys.SHOP_ITEM_PKEY;
    }

    @Override
    public List<ForeignKey<ShopItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHOP_ITEM__FK_SHOP_ITEM_SHOP);
    }

    private transient ShopPath _shop;

    /**
     * Get the implicit join path to the <code>itemstorage.shop</code> table.
     */
    public ShopPath shop() {
        if (_shop == null)
            _shop = new ShopPath(this, Keys.SHOP_ITEM__FK_SHOP_ITEM_SHOP, null);

        return _shop;
    }

    @Override
    public ShopItem as(String alias) {
        return new ShopItem(DSL.name(alias), this);
    }

    @Override
    public ShopItem as(Name alias) {
        return new ShopItem(alias, this);
    }

    @Override
    public ShopItem as(Table<?> alias) {
        return new ShopItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopItem rename(String name) {
        return new ShopItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopItem rename(Name name) {
        return new ShopItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopItem rename(Table<?> name) {
        return new ShopItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem where(Condition condition) {
        return new ShopItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShopItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShopItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
