/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.itemstorage.dal.entity.tables;


import com.jiubredeemer.itemstorage.dal.entity.Indexes;
import com.jiubredeemer.itemstorage.dal.entity.Itemstorage;
import com.jiubredeemer.itemstorage.dal.entity.Keys;
import com.jiubredeemer.itemstorage.dal.entity.tables.ShopItem.ShopItemPath;
import com.jiubredeemer.itemstorage.dal.entity.tables.records.ShopRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Shop extends TableImpl<ShopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>itemstorage.shop</code>
     */
    public static final Shop SHOP = new Shop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopRecord> getRecordType() {
        return ShopRecord.class;
    }

    /**
     * The column <code>itemstorage.shop.id</code>.
     */
    public final TableField<ShopRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop.room_id</code>.
     */
    public final TableField<ShopRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop.npc_id</code>.
     */
    public final TableField<ShopRecord, UUID> NPC_ID = createField(DSL.name("npc_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.shop.name</code>.
     */
    public final TableField<ShopRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>itemstorage.shop.description</code>.
     */
    public final TableField<ShopRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.shop.img_url</code>.
     */
    public final TableField<ShopRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>itemstorage.shop.created_by</code>.
     */
    public final TableField<ShopRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>itemstorage.shop.created_at</code>.
     */
    public final TableField<ShopRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Shop(Name alias, Table<ShopRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Shop(Name alias, Table<ShopRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>itemstorage.shop</code> table reference
     */
    public Shop(String alias) {
        this(DSL.name(alias), SHOP);
    }

    /**
     * Create an aliased <code>itemstorage.shop</code> table reference
     */
    public Shop(Name alias) {
        this(alias, SHOP);
    }

    /**
     * Create a <code>itemstorage.shop</code> table reference
     */
    public Shop() {
        this(DSL.name("shop"), null);
    }

    public <O extends Record> Shop(Table<O> path, ForeignKey<O, ShopRecord> childPath, InverseForeignKey<O, ShopRecord> parentPath) {
        super(path, childPath, parentPath, SHOP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShopPath extends Shop implements Path<ShopRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShopPath(Table<O> path, ForeignKey<O, ShopRecord> childPath, InverseForeignKey<O, ShopRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShopPath(Name alias, Table<ShopRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShopPath as(String alias) {
            return new ShopPath(DSL.name(alias), this);
        }

        @Override
        public ShopPath as(Name alias) {
            return new ShopPath(alias, this);
        }

        @Override
        public ShopPath as(Table<?> alias) {
            return new ShopPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Itemstorage.ITEMSTORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHOP_ROOM_ID_IDX);
    }

    @Override
    public UniqueKey<ShopRecord> getPrimaryKey() {
        return Keys.SHOP_PKEY;
    }

    private transient ShopItemPath _shopItem;

    /**
     * Get the implicit to-many join path to the
     * <code>itemstorage.shop_item</code> table
     */
    public ShopItemPath shopItem() {
        if (_shopItem == null)
            _shopItem = new ShopItemPath(this, null, Keys.SHOP_ITEM__FK_SHOP_ITEM_SHOP.getInverseKey());

        return _shopItem;
    }

    @Override
    public Shop as(String alias) {
        return new Shop(DSL.name(alias), this);
    }

    @Override
    public Shop as(Name alias) {
        return new Shop(alias, this);
    }

    @Override
    public Shop as(Table<?> alias) {
        return new Shop(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shop rename(String name) {
        return new Shop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shop rename(Name name) {
        return new Shop(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shop rename(Table<?> name) {
        return new Shop(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop where(Condition condition) {
        return new Shop(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shop where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shop where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shop where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shop where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shop whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
